spring:
  application:
    name: eureka-sv
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 0
